version: build {build}

image:
- Visual Studio 2019

build:
  verbosity: minimal

before_build:
- ps: |
    dotnet tool restore
    $env:SEMVER = dotnet nbgv get-version -v SemVer2
    Update-AppveyorBuild -Version "$env:SEMVER ($env:APPVEYOR_BUILD_ID)"
    dotnet paket restore

build_script:
- ps: | 
    dotnet build -c release
    dotnet paket pack $PWD/bin --version $env:SEMVER

test_script:
- ps: |
    dotnet test -c release --logger trx --results-directory $PWD/bin
    $failed = $LASTEXITCODE -ne 0
    $url = "https://ci.appveyor.com/api/testresults/mstest/$env:APPVEYOR_JOB_ID"
    ls bin/*.trx | % { (new-object System.Net.WebClient).UploadFile($url, $_) }
    if ($failed) { throw "$failCount tests failed" }

artifacts:
  - path: bin\*.nupkg
    name: nuget
