name: Build

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.402'

      - name: NuGet cache
        uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json') }}-${{ hashFiles('*.lock') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build
        run: |
          git checkout ("${{github.ref}}" -replace '^refs/[^/]+/','')
          dotnet tool restore
          dotnet paket restore
          dotnet build -c release

      - name: Test
        run: dotnet test -c release --logger trx --results-directory $PWD/bin/testresults

      - name: Pack
        run: |
          dotnet paket pack $PWD/bin/nuget --version (dotnet nbgv get-version -v SemVer2)

      - name: Upload nupkg
        uses: actions/upload-artifact@v1
        with:
          name: nuget
          path: bin/nuget

  release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ contains(github.ref, 'releases') || contains(github.ref, 'master') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.402'

      - name: Prepare
        run: |
          git checkout "$(echo ${{github.ref}} | sed -E 's|^refs/[^/]+/||')"
          dotnet tool restore
          echo "FULL_VERSION=$(dotnet nbgv get-version -v SemVer2)" >> $GITHUB_ENV
          echo "TAG_VERSION=$(dotnet nbgv get-version -v MajorMinorVersion)" >> $GITHUB_ENV

      - name: Create major-minor tag
        uses: ./.github/actions/github-tagger
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.TAG_VERSION }}
          move-existing: true

      - name: Create full tag
        uses: ./.github/actions/github-tagger
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.FULL_VERSION }}

      - name: Create draft release
        uses: Roang-zero1/github-create-release-action@master
        with:
          created_tag: v${{ env.TAG_VERSION }}
          create_draft: true
          update_existing: true
          release_title: Version ${{ env.TAG_VERSION }}
          changelog_heading: h2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}